[package]
name = "larkspur-common"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }
bytemuck = { version = "1.23.1", features = ["derive"] }

[lib]
path = "src/lib.rs"
